version: '2'

services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      main:
        aliases:
          - db
  
  mediawiki:
    build: .
    ports:
      - "80:80"
    links:
      - db
      - node-services
    volumes:
      - /var/lib/wiki/mediawiki:/data:rw
      # Inject our specific settings
  #   - ./conf/mediawiki:/conf:ro
    environment:
      MEDIAWIKI_SITE_SERVER: //wiki.local
      MEDIAWIKI_SITE_NAME: My Wiki
      MEDIAWIKI_SITE_LANG: en
      MEDIAWIKI_ADMIN_USER: admin
      MEDIAWIKI_ADMIN_PASS: rosebud
      MEDIAWIKI_UPDATE: 'true'
  #   MEDIAWIKI_VERSION: 1.25.3
      MEDIAWIKI_DB_USER: root
      MEDIAWIKI_DB_HOST: db
      MEDIAWIKI_DB_PASSWORD: root
  
      # Link to node services
      MEDIAWIKI_RESTBASE_URL: http://node-services:7231/localhost/v1
    networks:
      main:
        aliases:
          - mediawiki
  
  node-services:
    image: wikimedia/mediawiki-node-services
    # Temporarily expose RB port directly.
    # TODO: Set up rewrite at /api/rest_v1/.
    expose:
      - "7231"
      - "8142"
    volumes:
      - /var/lib/wiki/node-services:/data
    environment:
      MEDIAWIKI_API_URL: http://mediawiki/api.php
    networks:
      main:
        aliases:
          - node-services

networks:
  main:
